import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { db } from "@/db/index";
import { DM_Sans } from "next/font/google";
import { cn } from "../lib/utils";
import { SessionProvider } from "next-auth/react";

const dm_sans = DM_Sans({ subsets: ["latin"] });
const international = localfont({
  src: [
    {
      path: "../../public/fonts/nb_international_pro_light-webfont.woff2",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("DB in layout:", db);
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background antialiased h-screen",
          international.className
        )}
      >
        <SessionProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
